# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

svilf_interal_logit <- function(Y, H, prop = 2.0, sample_adaptive = FALSE, intercept = TRUE, eigen_init = FALSE, get_samples = 0L, tau = 1.0, kappa = 0.75, maxit = 100L, maxit_inner = 10L, print_each = 10L, tol = 1e-5) {
    .Call('_svilf_svilf_interal_logit', PACKAGE = 'svilf', Y, H, prop, sample_adaptive, intercept, eigen_init, get_samples, tau, kappa, maxit, maxit_inner, print_each, tol)
}

svilf_interal_probit <- function(Y, H, prop = 2.0, sample_adaptive = FALSE, intercept = TRUE, eigen_init = FALSE, get_samples = 0L, tau = 1.0, kappa = 0.75, maxit = 100L, maxit_inner = 10L, print_each = 10L, tol = 1e-5) {
    .Call('_svilf_svilf_interal_probit', PACKAGE = 'svilf', Y, H, prop, sample_adaptive, intercept, eigen_init, get_samples, tau, kappa, maxit, maxit_inner, print_each, tol)
}

eff_lowtri <- function(Y) {
    .Call('_svilf_eff_lowtri', PACKAGE = 'svilf', Y)
}

eff_cross_lt <- function(Y) {
    .Call('_svilf_eff_cross_lt', PACKAGE = 'svilf', Y)
}

id_lt <- function(vv, V) {
    .Call('_svilf_id_lt', PACKAGE = 'svilf', vv, V)
}

